#!/bin/sh

# TODO: make this sync with Makefile
SRC="recess"
LIB="lib$SRC.so"
INSTALL_PATH="$HOME/.local/bin"
RECESS_FILE="$INSTALL_PATH/$LIB"

shim() {
    if test -f "$RECESS_FILE"; then
        # execute
        LD_PRELOAD=$RECESS_FILE $@
    else
        echo "$RECESS_FILE not found"
        exit 1
    fi
}

# main
if [ $# -eq 0 ]; then
    echo "Usage: $0 <cmd>"
    exit 1
else
    shim $@
fi
